bookpage.webui/Models/ProductDetailModel.cs
using System.Collections.Generic;
using bookpage.entity;

namespace bookpage.webui.Models
{
    public class ProductDetailModel
    {//hem ürün hem category bilgisini bana taşıyacak olan bir yapı
        public Product product { get; set; }
        public List<Category> Category { get; set; }
    }
}

bookpage.webui/ViewModels/ProductListViewModel.cs
using System.Collections.Generic;
using bookpage.entity;

namespace bookpage.webui.ViewModels
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
    }
}

bookpage.webui/Controllers/BookController.cs
using bookpage.business.Abstract;
using bookpage.entity;
using bookpage.webui.Models;
using bookpage.webui.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace bookpage.webui.Controllers
{
    public class BookController:Controller
    {
        private IProductServices _productServices;
        public BookController(IProductServices productServices)
        {
            this._productServices=productServices;
        }
        public IActionResult List(string category)
        {
            var productsViewModel = new ProductListViewModel
            {
               Products = _productServices.GetProductsByCategory(category)
            };//bunu productviewmodel.csye gönderiyo onu viewde kullanıyo sonra onu ekrana basıyo

            return View(productsViewModel);
        }

        public IActionResult Details(int? id)
        {
            if(id==null)//eğer id yoksa hata sayfası ver
            {
                return NotFound();
            }
            Product productt=_productServices.GetProductDetails((int)id);//bunu getall dan getproddeta ile değiştirdim.

            if(productt==null)//eğer product yoksa hata sayfası
            {
                return NotFound();
            }
            //return View(productt);//buldunduysa bulduğu product bilgisini sayfaya mdel olarak gönderelim şimdi details cshtml düzenleyelim
               return View(new ProductDetailModel{//viewmodel içine paketledim
                 product = productt,
                 Category = productt.ProductCategories
                .Select(i=>i.Categories)// zaten vt'den sorguladığımız bir bilgi üstüne select işlemi yapabiliriz her gelen bilgi üzerinden kategoriye geçeriz
                .ToList()//ve almış olduğum her kategoriyi foreace kullanıyomuşum gibi i içine kopyaliycam ve gitmiş olduğum productun categorysine gidicem
            });//ürünü aldım kategorilerinide getirdim 1. telefonlar o veriyi post edeceksin ama elinde product ve category var ve başka categoryde varsa o ürnün hangi kategoriden geldiğini bilmen lazım oda bu
        }

        public IActionResult Read(int? id)
        {
            if(id==null)//eğer id yoksa hata sayfası ver
            {
                return NotFound();
            }
            Product productt=_productServices.GetProductDetails((int)id);//bize product bilgisi geliyor product bilgisi içerisinden productcategories ve ordanda categori bilgilerine geçiş yapabiliyoruz

            if(productt==null)//eğer product yoksa hata sayfası
            {
                return NotFound();
            }
           // return View(product);//buldunduysa bulduğu product bilgisini sayfaya mdel olarak gönderelim ve readcshtml'de bilgiler gözüksün
               return View(new ProductDetailModel{
                 product = productt,
                 Category = productt.ProductCategories.Select(i=>i.Categories).ToList()
             });
        }



    }
}

bookpage.webui/Controllers/ProductController.cs
using bookpage.business.Abstract;
using bookpage.data.Abstract;
using bookpage.entity;
using bookpage.webui.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.Linq;

namespace bookpage.webui.Controllers
{
    public class ProductController:Controller
    {
        private IProductServices _productServices;
        public ProductController(IProductServices productServices)
        {
            this._productServices=productServices;
        }
        public IActionResult Index()
        {
            var productsViewModel = new ProductListViewModel
            {
               Products = _productServices.GetAll()
            };

            return View(productsViewModel);
        }

        public IActionResult List(int? id,string q)
        {
           //var products=ProductRepository.Products;
            // if(id!=null)
            // {
            //     products=products.Where(p=>p.CategoryId==id).ToList();
            // }

            // if(!string.IsNullOrEmpty(q))
            // {
            //     products=products.Where(i=>i.Name.ToLower().Contains(q.ToLower())).ToList();
            // }
           
            var productsViewModel = new ProductListViewModel
             {
                Products = _productServices.GetAll()
             };

            return View(productsViewModel);
        }

        public IActionResult Details(int id)
        {
            return View();
            //id parametresini gönderdim ve viewüzerine bir pdourct nesnesi gönderiyor
        }

        public IActionResult Read(int id)
        {
            return View();
        }

        [HttpGet]
        public IActionResult Create()
        {
            //ViewBag.Categories=new SelectList(CategoryRepository.Categories,"CategoryId","Name");
            //return View(new Product());
            return View();
        }

        [HttpPost]
        public IActionResult Create(Product p)
        {
           // if(ModelState.IsValid)//beklediğimiz tüm bilgiler uyguladığımız kurallara göre oluştu.Productta
            //{
             // ProductRepository.Addproducts(p);
              return RedirectToAction("list");
            //}
             //ViewBag.Categories=new SelectList(CategoryRepository.Categories,"CategoryId","Name");
            //return View(p);//eğer yanlış girerse girdiği bilgilerle geldiği ekrana gitsin
           
            
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            //ViewBag.Categories=new SelectList(CategoryRepository.Categories,"CategoryId","Name");
           // return View(ProductRepository.GetProductById(id));
                       return View();

        }

        [HttpPost]
        public IActionResult Edit(Product p)
        {
            //ProductRepository.EditProduct(p);
            return RedirectToAction("list");
        }

        [HttpPost]
        public IActionResult Delete(int ProductId)
        {
           // ProductRepository.DeleteProduct(ProductId);
            return RedirectToAction("list");
        }
    }
}

bookpage.webui/ViewComponents/CategoriesViewComponent.cs
using System.Collections.Generic;
using bookpage.business.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace bookpage.webui.ViewComponents
{
    public class CategoriesViewComponent:ViewComponent//heryerde category var zaten o yüzden sürekli indexten almayayım diye bağımsız bir yapı oluşturuyorum
    {
        private ICategoryServices _categoryServices;
        public CategoriesViewComponent(ICategoryServices CategoryServices)
        {
            this._categoryServices=CategoryServices;
        }
        public IViewComponentResult Invoke()
        {
            if(RouteData.Values["category"]!=null)
            ViewBag.SelectedCategory=RouteData?.Values["category"];
           return View(_categoryServices.GetAll());//metodu categorylerimi getirir

        }
    }
}

bookpage.webui/Views/Book/Details.cshtml
@model ProductDetailModel

<div class="card mb-3 mt-3">
          <div class="card-body">
    <div class="row no-gutter">
        <div class="col-md-3">
            <img src="~/img/@Model.product.ImageUrl" class="card-img" alt="">
        </div>
        <div class="col-md-9">
                <h5 class="car-title">@Model.product.Name</h5>
                <p class="card-text">@Model.product.Author</p>
                <h6 class="card-text">@Model.product.Pages</h6>

                @foreach (var item in Model.Category)
                {
                   <a asp-controller="book" asp-action="list" asp-route-category="@item.Url" class="btn btn-link p-0 mb-3">@item.Name</a> 
                }
                <hr>
                @* <p class="card-text">@Model.Description</p> *@
            <a asp-controller="Book" asp-action="Read" asp-route-id="@Model.product.ProductId" class="btn btn-primary btn-sm">İncele</a> @*book details altındaki product bilgisine gidiyo giderkende productid gönderiyo biz id bilgisini alıyoruz ve o id bilgisine uyan kaydı book comtroller içerisinde kullanıcılara göstericez*@  
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <p class="p-3">@Model.product.Description</p> Burada Özet kısmı olcak
        </div>
    </div>
</div>  
   </div>

bookpage.webui/Views/Book/List.cshtml
@model ProductListViewModel //yol
@{//buranın layoultla alakası yok
    var popularClass=Model.Products.Count>2?"popular":""; 
    var products=Model.Products;
}

    
@* @section Categories{
   @await Component.InvokeAsync("Categories")
} *@

<div class="row">
    <div class="col-md-3"> @*üçlük kısma category gelsin*@
           @await Component.InvokeAsync("Categories")
    </div>
    <div class="col-md-9">
       <div class="row">
              
                    <div class="row">                  
                        @foreach (var product in products)
                        {    
                        <div class="col-md-4">
                            @await Html.PartialAsync("_product",product) @* dinamik olduğu için obje bejler bende product u veririm*@
                            @* Listeden gelen her product objesini _productcshtml e gönderiyoruz ve gönderdiğimiz obje product prodyccshtml tarafından karşılanıyor ve karşılanan bilgi içerinden modelname desc yazdırılır *@
                        </div>       
                        }   
                    </div>
        </div>      
    </div>
</div>

        
             

bookpage.webui/Views/Book/Read.cshtml
@model ProductDetailModel
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/lib/bootstrap.min.css">
  <script src="/lib/jquery-1.12.2.min.js"></script>
  <script src="/lib/bootstrap.min.js"></script>
</head>

<div class="p-3 mt-2 mb-2 bg-dark text-white card-top">@Model.product.Name</div>
<div class="accordion" id="accordionExample">

  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Giriş
        </button>
      </h2>
    </div>
     <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
          @Model.product.Author
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Bölüm 1
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
          @Model.product.Description
      </div>
    </div>
  </div>
  

</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

bookpage.webui/Views/Product/create.cshtml
@model Product

<form method="POST">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
        <span asp-validation-for="Name" class="text-danger" ></span>
    </div>
    <div class="form-group">
        <label for="Author">Author</label>
        <input asp-for="Author" value="@Model.Author" class="form-control">
        <span asp-validation-for="Author" class="text-danger" ></span>
    </div>
    <div class="form-group">
        <label for="Pages">Pages</label>
        <input asp-for="Pages" value="@Model.Pages" class="form-control">
        <span asp-validation-for="Pages" class="text-danger" ></span>
    </div>
    @* <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description" value="@Model.Description" class="form-control"></textarea>
        <span asp-validation-for="Description" class="text-danger" ></span>
    </div>
    <div class="form-group">
        <label for="Door">Door</label>
        <input asp-for="Door" value="@Model.Door" class="form-control">
        <span asp-validation-for="Door" class="text-danger" ></span>
    </div>
    <div class="form-group">
       <label for="Moduls1">Moduls1</label>
       <textarea asp-for="Moduls1" value="@Model.Moduls1" class="form-control"></textarea>
       <span asp-validation-for="Moduls1" class="text-danger" ></span>
    </div>
    <div class="form-group">
        <label for="Moduls2">Moduls2</label>
        <textarea asp-for="Moduls2" value="@Model.Moduls2"  class="form-control"></textarea>
        <span asp-validation-for="Moduls2" class="text-danger" ></span>
    </div>
    <div class="form-group">
        <label for="Moduls3">Moduls3</label>
        <textarea asp-for="Moduls3" value="@Model.Moduls3"  class="form-control"></textarea>
        <span asp-validation-for="Moduls3" class="text-danger" ></span>
    </div>
    <div class="form-group">
        <label for="Moduls4">Moduls4</label>
        <textarea asp-for="Moduls4" value="@Model.Moduls4"  class="form-control"></textarea>
        <span asp-validation-for="Moduls4" class="text-danger" ></span>
    </div> *@
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl"  class="form-control">
        <span asp-validation-for="ImageUrl" class="text-danger" ></span>
    </div>
    @* <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control"> @*category idimleri gelir ama id olarak gönderir value alanına catid texte isim
            <option selected disabled>Seçiniz</option>
        </select>
        <span asp-validation-for="CategoryId" class="text-danger" ></span>
    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

bookpage.webui/Views/Product/details.cshtml
@model Product
@section Categories{
    @await Component.InvokeAsync("Categories")
}

<div class="card mb-3 mt-3">
          <div class="card-body">
    <div class="row no-gutter">
        <div class="col-md-3">
            <img src="~/img/@Model.ImageUrl" class="card-img" alt="">
        </div>
        <div class="col-md-9">
                <h5 class="car-title">@Model.Name</h5>
                <p class="card-text">@Model.Author</p>
                <p class="card-text">@Model.Pages</p>
                @* <p class="card-text">@Model.Description</p> *@
                <a href="/Product/read/@Model.ProductId" class="btn btn-primary mt-5">Oku</a>   

        </div>
    </div>
</div>     </div>

bookpage.webui/Views/Product/edit.cshtml
@model Product

<form method="POST">
    <input type="hidden" name="ProductId" value="@Model.ProductId">
    <div class="form-group">
        <label for="Name">Name</label>
        <input asp-for="Name" value="@Model.Name" class="form-control">
    </div>
    <div class="form-group">
        <label for="Author">Author</label>
        <input asp-for="Author" value="@Model.Author"  class="form-control">
    </div>
    <div class="form-group">
        <label for="Pages">Pages</label>
        <input asp-for="Pages" value="@Model.Pages" class="form-control">
    </div>
    @* <div class="form-group">
        <label for="Description">Description</label>
        <textarea asp-for="Description"  value="@Model.Description"  class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="Door">Door</label>
        <input asp-for="Door"  value="@Model.Door"  class="form-control">
    </div>
    <div class="form-group">
        <label for="Moduls1">Moduls1</label>
       <textarea asp-for="Moduls1"  value="@Model.Moduls1"  class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="Moduls2">Moduls2</label>
        <textarea asp-for="Moduls2" value="@Model.Moduls2"  class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="Moduls3">Moduls3</label>
        <textarea asp-for="Moduls3" value="@Model.Moduls3"  class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="Moduls4">Moduls4</label>
        <textarea asp-for="Moduls4" value="@Model.Moduls4"  class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label for="ImageUrl">ImageUrl</label>
        <input asp-for="ImageUrl" value="@Model.ImageUrl"  class="form-control">
    </div>
    <div class="form-group">
        <label for="CategoryId">CategoryId</label>
        <select asp-for="CategoryId" asp-items="@ViewBag.Categories" class="form-control"> @*category idimleri gelir ama id olarak gönderir value alanına catid texte isim
            <option selected disabled>Seçiniz</option>
        </select>
                    <span asp-validation-for="CategoryId" class="text-danger" ></span>
    </div> *@
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

bookpage.webui/Views/Product/index.cshtml
@model ProductListViewModel
    

<partial name="_header">
        
@if(Model.Products.Count==0)
{
   @await Html.PartialAsync("_product");
}
else
{
   <div class="row">                  
                        @foreach (var product in @Model.Products)
                        {    
                        <div class="col-md-4">
                            @await Html.PartialAsync("_product",product)
                        </div>       
                        
                        }   
                    </div>
}

bookpage.webui/Views/Product/list.cshtml
@model ProductListViewModel //yol
@{//buranın layoultla alakası yok
    var popularClass=Model.Products.Count>2?"popular":""; 
    var products=Model.Products;
}

    
@* @section Categories{
   @await Component.InvokeAsync("Categories")
} *@
@section Hedaer
{
   @await Html.PartialAsync("_header")
}
        
                @if(products.Count ==0 )
                {
                @await Html.PartialAsync("_noproduct")
                }
                else
                {
                    <div class="row">                  
                        @foreach (var product in products)
                        {    
                        <div class="col-md-4">
                            @await Html.PartialAsync("_product",product) @* dinamik olduğu için obje bejler bende product u veririm*@
                            @* Listeden gelen her product objesini _productcshtml e gönderiyoruz ve gönderdiğimiz obje product prodyccshtml tarafından karşılanıyor ve karşılanan bilgi içerinden modelname desc yazdırılır *@
                        </div>       
                        
                        }   
                    </div>
                }
             

bookpage.webui/Views/Product/read.cshtml
@model Product
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="/lib/bootstrap.min.css">
  <script src="/lib/jquery-1.12.2.min.js"></script>
  <script src="/lib/bootstrap.min.js"></script>
</head>

<div class="p-3 mt-2 mb-2 bg-dark text-white card-top">@Model.Name</div>

<div class="accordion" id="accordionExample">

  <div class="card">
    <div class="card-header" id="headingOne">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Giriş
        </button>
      </h2>
    </div>
    @* <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
          @Model.Door
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingTwo">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Bölüm 1
        </button>
      </h2>
    </div>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
          @Model.Moduls1
      </div>
    </div>
  </div>
  <div class="card">
    <div class="card-header" id="headingThree">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
         Bölüm 2
        </button>
      </h2>
    </div>
    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
      <div class="card-body">
          @Model.Moduls2
      </div>
    </div>
  </div>

 <div class="card">
    <div class="card-header" id="headingFour">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Bölüm-3
        </button>
      </h2>
    </div>
    <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordionExample">
      <div class="card-body">
          @Model.Moduls3
       </div>
    </div>
  </div>

 <div class="card">
    <div class="card-header" id="headingFive">
      <h2 class="mb-0">
        <button class="btn btn-link btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Bölüm 4
        </button>
      </h2>
    </div>
    <div id="collapseFive" class="collapse" aria-labelledby="headingFive" data-parent="#accordionExample">
      <div class="card-body">
       @Model.Moduls4
      </div>
    </div>
  </div> *@


</div>


<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

bookpage.webui/Views/Shared/Components/Categories/default.cshtml
@model List<Category>
<div class="list-group">
<a href="/products" class="list-group-item list-group-item-action">Tüm Kategoriler</a>
                       @foreach (var item in Model)
                      {
                        <a asp-controller="book" asp-action="list" asp-route-category="@item.Url"          
                      class="list-group-item list-group-item-action @(ViewBag.SelectedCategory == @item.Url?"active":"")">
                      @item.Name
                      </a>                  
                      }
                  </div> 

bookpage.webui/Views/Shared/_Layoult.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BookApp</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

</head>
<body>
    

    @await Html.PartialAsync("_navbar")

    <main class="mb-3">
        <div class="container"> 

                 <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                 </div>   
        
        </div>
    </main>

    <footer class="py-5 bg-dark text-white text-center">
        eBookApp | 2020
    </footer>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.8.1/css/all.css">

    @RenderSection("Scripts",false)
</body>
</html>

bookpage.webui/Views/Shared/_categories.cshtml
@model List<Category>
<div class="list-group">
                      @* @foreach (var category in Model)
                      {
                      <a href="" class="list-group-item list-group-item-action">@category.Name</a>
                      } *@
                      <a href="/product/list" class="list-group-item list-group-item-action">Tüm Kategoriler</a>
<a href="/product/list" class="list-group-item list-group-item-action">Telefon</a>
<a href="/product/list" class="list-group-item list-group-item-action">Bilgisayar</a>
                  </div>

bookpage.webui/Views/Shared/_header.cshtml
<header>
        <div class="jumbotron jumbotron-fluit">
            <div class="container">
                <h1 class="display-4">Book App</h1>
                <p class="lead">lorem 20</p>
            </div>
        </div>
    </header>

bookpage.webui/Views/Shared/_navbar.cshtml
<div class="navbar bg-primary navbar-dark navbar-expand-sm">
        <div class="container">
            <a href="/" class="navbar-brand">Book App</a>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
               <a href="/products" class="nav-link">Products</a>           
            <li class="nav-item">
                <a href="" class="nav-link">Cart</a>
            </li>
            <li class="nav-item">
                <a href="" class="nav-link">Orders</a>
            </li>
            <li class="nav-item">
                <a href="/product/create" class="nav-link">Add Product</a>
            </li>
            <li class="nav-item">
                <a asp-controller="admin" asp-action="createproduct" class="nav-link">Admin Create</a>
            </li>
            <li class="nav-item">
                <a asp-controller="book" asp-action="productlist" class="nav-link">Admin Products</a>
            </li>
        </ul>
         <form action="/product/list" class="form-inline">
                <input name="q" type="text" class="form-control mr-2" placeholder="Search">
                <button type="submit" class="btn btn-outline-light mr-0">Search</button>
            </form>
        </div>
    </div>

bookpage.webui/Views/Shared/_noproduct.cshtml
<div class="row">
        <div class="col-md-12">
           <div class="alert alert-danger"> Ürün Yok</div>
        </div>
     </div>

bookpage.webui/Views/Shared/_product.cshtml
@model Product 
 <div class="card mb-2">
            <img class="card-img-top" src="~/img/@Model.ImageUrl" alt="">
            <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <small class="text-muted">
            <i class="fas fa-lira-sing"><h5>Sayfa Sayısı</h5> @Model.Pages</i>
            </small>
             <p class="card-text"><h5>Kitabın Yazarı</h5>@Model.Author</p> 
            </div>
            <div class="card-footer text-center">
            <a asp-controller="Book" asp-action="Details" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">İncele</a> @*book details altındaki product bilgisine gidiyo giderkende productid gönderiyo biz id bilgisini alıyoruz ve o id bilgisine uyan kaydı book comtroller içerisinde kullanıcılara göstericez*@  
            <a asp-controller="Book" asp-action="AddToCard" asp-route-id="@Model.ProductId" class="btn btn-primary btn-sm">Card</a>   
            </div>
   </div> 
   
   
   
   
   
   
   @*   <a href="/product/edit/@Model.ProductId" class="btn btn-primary btn-sm">Güncelle</a>   
            <form method="POST" action="/product/delete" style="display:inline;">
                <input type="hidden" name="ProductId" value="@Model.ProductId" > 
            <button type="submit" class="btn btn-danger btn-sm">Sil</button>   
            </form> *@